targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.codegen.dart
       mockito|mockBuilder:
        generate_for:
          - test/*/*.dart
